apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/terasky.com_resourcepatches.yaml
  - bases/terasky.com_clusterresourcepatches.yaml
  - bases/terasky.com_sharedresources.yaml
  - bases/terasky.com_clustersharedresources.yaml
